### ISSUE TITLE
v1.0.0 Checklist

### ISSUE THREAD

**Issue by nordfjord** [equinox-project/equinox-js#27]
- [x] Document DynamoStore
- [x] Codec Interop with FsCodec
- [x] Propeller
- [x] Propeller telemetry beyond handler spans
- [x] Propeller retries
- [x] Prove out CDK
- [x] Integrated way to install message-db
- [x] Get someone to review the docs

**Comment by cloudcompute** [comment]
Hi @nordfjord 

Is this library stable, can we use it in production?

**Comment by nordfjord** [comment]
It’s stabilising as we speak. The message-db store is being used in production by a few people including my employer. The dynamo store has not seen production usage yet. It’s a port of the F# version and I believe there’s at least two production users of that version.

We’re have an equinox channel on the DDD/CQRS/ES discord if you want to chat/ideate!

https://discord.gg/nPMCupfEc7

**Comment by nordfjord** [comment]
To be clear, the messagedb store is production ready, but I would hold off on the dynamostore for now, unless you’d like to become the first production user with everything that entails.

**Comment by cloudcompute** [comment]
Thank you the quick responses. I'd prefer PostgreSQL (MessageDB) to DynamoDB.

Is this kind of architecture (comprising 3 layers/processes) possible, does it even make sense?

- Web controller layer/process dispatches the commands.

- Command handler is an intermediate layer comprising the business logic and publishes two types of events: a. Domain (internal, private to a microservice) events b. Integration events (exposed outside of the service)

c. Event sourcing process (equinox-js, in this case) does the 3 things: a. event sourcing (store domain events in a db) b. implement Outbox table (store integration events temporarily) c. Write integration events to Kafka i.e. doing the job of Kafka producer

The intermediate Command handler is what I want to be language-independent.

**Comment by nordfjord** [comment]
Thanks for this. I’m on mobile at the moment, but I’ll come back to you with a well formed response in a few hours! In the meantime I really do recommend joining the discord, we’re a friendly bunch who have a lot of experience building event sourced applications.

**Comment by cloudcompute** [comment]
Thank you, I will surely join tomorrow.

**Comment by nordfjord** [comment]
> Thank you the quick responses. I'd prefer PostgreSQL (MessageDB) to DynamoDB.
> Putting my application into production will take several months and I can hope
> this library will be quite mature by then.

> Is this kind of architecture (comprising 3 layers/processes) possible, does it
> even make sense?
>
> 1. Web controller layer/process dispatches the commands.

We tend to avoid the Command terminology in equinox. It tends to look great for
toy examples, but as soon as you get into real-world territory we've found it
more a hinderance than a help.

If you think about it there's not much difference between an object representing
a Command and a function.

```ts
type Command =
  | { type: "Increment"; data: { by: number } }
  | { type: "Decrement"; data: { by: number } };

type State = number;

const decide = (command: Command) => (state: State) => {
  switch (command.type) {
    case "Increment":
      return state < 10
        ? [{ type: "Incremented", data: { by: command.data.by } }]
        : [];
    case "Decrement":
      return state > 0
        ? [{ type: "Incremented", data: { by: command.data.by } }]
        : [];
  }
};
```

vs

```ts
namespace Decide {
  export const increment = (by: number) => (state: State) =>
    state < 10 ? [{ type: "Incremented", data: { by } }] : [];
  export const decrement = (by: number) => (state: State) =>
    state > 0 ? [{ type: "Incremented", data: { by } }] : [];
}
```

What we preach is that a single "CommandBus" is detrimental to your
architecture. Instead we choose to instantiate domain service and call methods
on them directly. With the counter example above the domain service might look
like

```ts
class Service {
  constructor(
    private readonly resolve: (id: string) => Decider<Event, State>,
  ) {}

  increment(id: string, by: number) {
    const decider = this.resolve(id);
    return decider.transact(Decide.increment(by));
  }
  decrement(id: string, by: number) {
    const decider = this.resolve(id);
    return decider.transact(Decide.decrement(by));
  }

  // prettier-ignore
  static createMem(store: VolatileStore) {
    const category = MemoryStoreCategory.create(store, categoryName, codec, fold, initial)
    const resolve = (id: string) => Decider.forStream(category, streamId(id), null);
    return new Service(resolve);
  }
}
```

And in your http/message-handler/whatever layer you'd construct this service and
use it

```ts
class CounterConsumer {
  constructor(
    private kafka: Kafka,
    private counter: Counter.Service,
  ) {}

  async start(signal: AbortSignal) {
    const consumer = createConsumer(this.kafka);
    consumer.run({
      async eachMessage(msg) {
        await counter.increment(getId(msg.value), getCount(msg.value));
      },
    });
  }
}
```

There's a full example application including read-models avalaible in the [source](https://github.com/nordfjord/equinox-js/tree/main/apps/example)

> 2. Command handler is an intermediate layer comprising the business logic and
>    publishes two types of events: a. Domain (internal, private to a microservice)
>    events b. Integration events (exposed outside of the service)

I would wholeheartedly advise against this architecture. Your service is part
of a context and if it needs to expose integration events for other services
that should be done the same way you create read models, with a consumer tailing
your store.

```ts
function createHandler(kafka: KafkaProducer) {
  return async (stream: StreamName, events: ITimelineEvent[]) => {
    await kafka.send({
      topic: TOPIC,
      messages: await mapToIntegrationEvents(stream, events),
    });
  };
}
async function main(signal: AbortSignal) {
  const kafkaProducer = createKafkaProducer(signal);
  const handler = createHandler(kafkaProducer);
  const source = MessageDbSource.create({
    pool: followerPool() ?? leaderPool(),
    batchSize: 500,
    categories: ["MyCategory"],
    groupName: "IntegrationEvents",
    checkpoints,
    handler: handle,
    tailSleepIntervalMs: 100,
    maxConcurrentStreams: 10,
  });

  await source.start(signal);
}
```

> 3. Event sourcing process (equinox-js, in this case) does the 3 things: a. event
>    sourcing (store domain events in a db) b. implement Outbox table (store
>    integration events temporarily) c. Write integration events to Kafka i.e. doing
>    the job of Kafka producer

See above

> The intermediate Command handler is what I want to be language-independent.

I'd say having your events stored in message-db is enough for them to be
interoperable in many languages, we have services written in JS and F# using the
same message-db instance for storage and reading the same events in some cases.

Hope this helps, and again, feel free to reach out on the discord to talk about
these sorts of architectures in more detail!

**Comment by nordfjord** [comment]
1.0 is already out for a while, closing this
